/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jerin' at '4/2/17 7:41 PM' with Gradle 2.14.1
 *
 * @author jerin, @date 4/2/17 7:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
